version: 2.1
orbs:
  vault: contentful/vault@1
executors:
  node:
    docker:
      - image: cimg/node:16.13.2
jobs:
  test:
    executor: node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run tests
          command: npm test
  lint:
    executor: node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Lint project
          command: npm run lint
  lint-commits:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: npm ci
          command: npm ci
      - run:
          name: Linting commits
          command: npm run commitlint-circle
  semantic-release:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - vault/get-secrets: # Loads vault secrets
          template-preset: 'semantic-release'
      - run:
          name: npm ci
          command: npm ci
      - run:
          name: Releasing
          command: npm run semantic-release
workflows:
  test:
    jobs:
      - lint
      - test
      - lint-commits
      - semantic-release:
          context: vault
          requires:
            - lint
            - test
            - lint-commits
