version: 2.1
orbs:
  vault: contentful/vault@1
executors:
  node:
    docker:
      - image: cimg/node:lts
jobs:
  test:
    executor: node
	jobs:
      - run:
          name: Lint project
          command: npm run lint
  semantic-release:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - vault/get-secrets: # Loads vault secrets
	workflows:
    jobs:
      - lint
      - test
      - semantic-release:
          context: vault
          requires:
            - lint
            - test
